### PR TITLE
fix(builder): filter self-referencing validations

### PR DESCRIPTION
**Pull request by HannesT117**
See #19 

Not sure where to best filter the validations, this was my initial approach to fix the issue.

### CODE REVIEW

**Comment by marcolink** [comment]
Hi @HannesT117 thanks for the PR!

while i was looking at your solution, I was wondering if it's possible to find a single point in code where we could strip out self referencing imports. 

So i came to this solution here: #23 

What do you think?

**Comment by HannesT117** [comment]
Cool, I was quite sure that I had missed something - looks good :) Closing this PR therefore.

**Comment by marcolink** [comment]
@HannesT117 I merged mine - happy referencing :)

**Comment by HannesT117** [comment]
@marcolink perfect, thanks a lot!

**Pull request closed without merging**
